ASD = {
    "CIFAR10":{
        "ResNet18":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/ResNet18/BadNets/2025-02-04_13:08:56/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/ResNet18/BadNets/2025-05-05_13:37:35/ckpt/latest_model.pt",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/ResNet18/IAD/2025-02-17_17:27:09/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/ResNet18/IAD/2025-05-05_13:43:27/ckpt/latest_model.pt",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/ResNet18/Refool/2025-02-17_17:49:37/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/ResNet18/Refool/2025-05-05_13:49:42/ckpt/latest_model.pt",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/ResNet18/WaNet/2025-02-17_18:19:07/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/ResNet18/WaNet/2025-05-05_14:01:45/ckpt/latest_model.pt",
                "exp_3":""
            }
        },
        "VGG19":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/VGG19/BadNets/2025-02-17_18:25:45/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/VGG19/BadNets/2025-05-05_14:13:59/ckpt/latest_model.pt",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/VGG19/IAD/2025-02-17_18:29:21/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/VGG19/IAD/2025-05-05_14:49:59/ckpt/latest_model.pt",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/VGG19/Refool/2025-02-27_11:52:39/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/VGG19/Refool/2025-05-05_15:09:45/ckpt/latest_model.pt",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/VGG19/WaNet/2025-02-17_18:34:34/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/VGG19/WaNet/2025-05-05_15:25:23/ckpt/latest_model.pt",
                "exp_3":""
            }
        },
        "DenseNet":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/DenseNet/BadNets/2025-02-17_18:39:21/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/DenseNet/IAD/2025-02-17_18:41:23/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/DenseNet/Refool/2025-02-17_18:47:05/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/CIFAR10/DenseNet/WaNet/2025-02-17_18:59:49/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            }
        }
    },
    "GTSRB":{
        "ResNet18":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/ResNet18/BadNets/2025-02-17_18:54:05/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/ResNet18/BadNets/2025-05-05_17:51:08/ckpt/latest_model.pt",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/ResNet18/IAD/2025-02-17_18:57:13/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/ResNet18/IAD/2025-05-05_18:09:26/ckpt/latest_model.pt",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/ResNet18/Refool/2025-02-17_19:40:32/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/ResNet18/Refool/2025-05-05_18:39:23/ckpt/latest_model.pt",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/ResNet18/WaNet/2025-02-17_20:01:40/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/ResNet18/WaNet/2025-05-05_18:43:50/ckpt/latest_model.pt",
                "exp_3":""
            }
        },
        "VGG19":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/VGG19/BadNets/2025-02-17_20:02:49/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/VGG19/BadNets/2025-05-05_19:05:00/ckpt/latest_model.pt",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/VGG19/IAD/2025-02-17_20:05:46/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/VGG19/IAD/2025-05-05_19:08:03/ckpt/latest_model.pt",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/VGG19/Refool/2025-02-17_20:28:34/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/VGG19/Refool/2025-05-05_19:17:12/ckpt/latest_model.pt",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/VGG19/WaNet/2025-02-17_20:31:08/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/VGG19/WaNet/2025-05-05_20:33:23/ckpt/latest_model.pt",
                "exp_3":""
            }
        },
        "DenseNet":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/DenseNet/BadNets/2025-02-17_20:32:50/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/DenseNet/IAD/2025-02-17_20:35:23/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/DenseNet/Refool/2025-02-17_20:40:02/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/GTSRB/DenseNet/WaNet/2025-02-17_20:44:25/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            }
        }
    },
    "ImageNet2012_subset":{
        "ResNet18":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/ResNet18/BadNets/2025-03-07_13:55:26/ckpt/latest_model.pt",
                "exp_2":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/ResNet18/BadNets/2025-05-06_12:47:16/ckpt/latest_model.pt",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/ResNet18/IAD/2025-03-07_20:28:50/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/ResNet18/Refool/2025-03-07_21:03:57/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/ResNet18/WaNet/2025-03-07_21:31:50/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            }
        },
        "DenseNet":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/DenseNet/BadNets/2025-03-12_11:30:35/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/DenseNet/IAD/2025-03-12_11:40:01/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/DenseNet/Refool/2025-03-14_11:10:26/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/ASD/ImageNet2012_subset/DenseNet/WaNet/2025-03-14_12:34:37/ckpt/latest_model.pt",
                "exp_2":"",
                "exp_3":""
            }
        }
    }
}

Our = {
    "CIFAR10":{
        "ResNet18":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/ResNet18/BadNets/2025-04-30_22:12:52/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/ResNet18/IAD/2025-04-30_22:19:26/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/ResNet18/Refool/2025-04-30_22:26:50/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/ResNet18/WaNet/2025-04-30_22:33:15/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            }
        },
        "VGG19":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/VGG19/BadNets/2025-04-30_22:40:50/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/VGG19/IAD/2025-04-30_22:53:48/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/VGG19/Refool/2025-04-30_22:55:03/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/VGG19/WaNet/2025-04-30_22:58:41/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            }
        },
        "DenseNet":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/DenseNet/BadNets/2025-04-30_23:11:52/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/DenseNet/IAD/2025-04-30_23:13:52/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/DenseNet/Refool/2025-04-30_23:15:54/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/CIFAR10/DenseNet/WaNet/2025-04-30_23:17:33/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            }
        }
    },
    "GTSRB":{
        "ResNet18":{
            "BadNets":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/GTSRB/ResNet18/BadNets/2025-05-02_20:11:49/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/GTSRB/ResNet18/IAD/2025-05-02_20:14:10/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"/data/mml/backdoor_detect/experiments/OurMethod/Retrain/GTSRB/ResNet18/Refool/2025-05-02_20:20:12/best_ft_model.pth",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            }
        },
        "VGG19":{
            "BadNets":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            }
        },
        "DenseNet":{
            "BadNets":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            }
        }
    },
    "ImageNet2012_subset":{
        "ResNet18":{
            "BadNets":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            }
        },
        "DenseNet":{
            "BadNets":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "IAD":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "Refool":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            },
            "WaNet":{
                "exp_1":"",
                "exp_2":"",
                "exp_3":""
            }
        }
    }
}